<?xml version="1.0"?>

<robot name="iris" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="namespace" value="" />
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="mesh_file" value="iris.stl" />
  <xacro:property name="mesh_scale" value="1 1 1"/>
  <xacro:property name="mesh_scale_prop" value="1 1 1"/>
  <xacro:property name="mass" value="1.5" /> <!-- [kg] -->
  <xacro:property name="body_width" value="0.47" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.11" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.005" /> <!-- [kg] -->
  <xacro:property name="arm_length_front_x" value="0.13" /> <!-- [m] -->
  <xacro:property name="arm_length_back_x" value="0.13" /> <!-- [m] -->
  <xacro:property name="arm_length_front_y" value="0.22" /> <!-- [m] -->
  <xacro:property name="arm_length_back_y" value="0.2" /> <!-- [m] -->
  <xacro:property name="rotor_offset_top" value="0.023" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.128" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="8.54858e-06" /> <!-- [kg.m/s^2] -->
  <xacro:property name="moment_constant" value="0.06" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.025" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="1100" /> <!-- [rad/s] -->
  <xacro:property name="sin30" value="0.5" />
  <xacro:property name="PI" value="3.14159265359" />
  <xacro:property name="cos30" value="0.866025403784" />
  <xacro:property name="sqrt2" value="1.4142135623730951" />
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-04" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />
  <xacro:property name="color" value="$(arg visual_material)" />
  <xacro:property name="length_pole" value="0.25" /><!-- [m] -->
  <xacro:property name="mass_pole" value="0.001" /><!-- [kg] -->
  <xacro:property name="radius_pole" value="0.001" /><!-- [m] -->



  <!-- Property Blocks -->
  <xacro:property name="body_inertia">
    <inertia 
    ixx="${1/12 * mass * (body_height * body_height + body_width * body_width)}"
    iyy="${1/12 * mass * (body_height * body_height + body_width * body_width)}"
    izz="${1/12 * mass * (body_width * body_width + body_width * body_width)}"    
    ixy="0.0" ixz="0.0" iyz="0.0" /> <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
  <xacro:property name="rotor_inertia">
    <inertia
    ixx="${1/12 * mass_rotor * (0.015 * 0.015 + 0.003 * 0.003) * rotor_velocity_slowdown_sim}"
    iyy="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.003 * 0.003) * rotor_velocity_slowdown_sim}"
    izz="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.015 * 0.015) * rotor_velocity_slowdown_sim}"
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(arg rotors_description_dir)/urdf/multirotor_base.xacro" />

  <!-- Instantiate multirotor_base_macro once -->
  <xacro:multirotor_base_macro
    robot_namespace="${namespace}"
    mass="${mass}"
    body_width="${body_width}"
    body_height="${body_height}"
    mesh_file="${mesh_file}"
    mesh_scale="${mesh_scale}"
    color="${color}"
    >
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <!-- Instantiate rotors -->
  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh="iris_prop"
    mesh_scale="${mesh_scale_prop}"
    color="Blue">
    <origin xyz="${arm_length_front_x} -${arm_length_front_y} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="back_left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh="iris_prop"
    mesh_scale="${mesh_scale_prop}"
    color="DarkGrey">
    <origin xyz="-${arm_length_back_x} ${arm_length_back_y} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="front_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh="iris_prop"
    mesh_scale="${mesh_scale_prop}"
    color="Blue">
    <origin xyz="${arm_length_front_x} ${arm_length_front_y} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="back_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh="iris_prop"
    mesh_scale="${mesh_scale_prop}"
    color="DarkGrey">
    <origin xyz="-${arm_length_back_x} -${arm_length_back_y} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>


   <!--joint name="base_to_pole" type="revolute">
    <parent link="base_link"/>
    <child link="pole"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="${-PI}" upper = "${PI}" velocity="1000.0"/>
  </joint>

  < Pole Link -->
  <!--link name="pole">
    < <collision>
      <origin xyz="0 0 ${length_pole/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${radius_pole} ${radius_pole} ${length_pole}"/>
      </geometry>
    </collision> -->

    <!--visual>
      <origin xyz="0 0 ${length_pole/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${radius_pole} ${radius_pole} ${length_pole}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${length_pole/2}" rpy="0 0 0"/>
      <mass value="0.0"/>
      <inertia
    ixx="${mass_pole*length_pole*length_pole/300}" ixy="0.0" ixz="0.0"
    iyy="0.0" iyz="0.0"
    izz="${mass_pole*length_pole*length_pole/300}"/>
    </inertial>
  </link-->

    <!-- planar arm -->

  <link name="link1">
        <origin xyz="0 0 0.0" rpy="0 0 0"/>
        <inertial>
            <mass value="0.001"/>
            <inertia ixx="0.00203125/1000" iyy="0.00203125/1000" izz="0.0003125/1000" ixy="0" iyz="0" ixz="0"/>
        </inertial>
        <!--collision>
            <geometry>
                <cylinder radius="0.025" length="0.15"/>
            </geometry>
        </collision-->
        <visual>
            <geometry>
              <cylinder radius="0.025" length="0.15"/>
            </geometry>
        </visual>
    </link>

    <!-- base link 1 joint-->
    <joint name="base_link1_joint" type="revolute">
        <origin xyz="0 0 0" rpy = "0 ${PI}$ 0"/>
        <parent link="base_link"/>
        <child link="link1"/>
        <axis xyz="0 1 0"/>
        <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5"/>
    </joint>

<!-- link 2 -->

    <link name="link2">
        <origin xyz="0 0 0.15/2" rpy="0 0 0"/>
        <inertial>
            <mass value="0.001"/>
            <inertia ixx="0.00203125/1000" iyy="0.00203125/1000" izz="0.0003125/1000" ixy="0" iyz="0" ixz="0"/>
        </inertial>
        <!--collision>
            <geometry>
                <cylinder radius="0.025" length="0.15"/>
            </geometry>
        </collision-->
        <visual>
            <geometry>
              <cylinder radius="0.025" length="0.15"/>
            </geometry>
        </visual>
    </link>

    <!-- base link 2 joint-->
    <joint name="base_link2_joint" type="revolute">
        <origin xyz="0 0 0.15"/>
        <parent link="link1"/>
        <child link="link2"/>
        <axis xyz="0 1 0"/>
        <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5"/>
    </joint>

    <gazebo>
        <plugin name="ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/</robotNamespace>
      </plugin>
    </gazebo>

    <transmission name="trans_id_1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_link1_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor1">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>6.7</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="trans_id_2">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_link2_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor2">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>6.7</mechanicalReduction>
        </actuator>
    </transmission>

    <gazebo reference="link1">
      <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="link2">
      <material>Gazebo/Green</material>
    </gazebo>

    

    


</robot>
